server:
  port: 8080

spring:
  application:
    name: gerenciador-cadastro

  datasource:
    url: jdbc:mysql://localhost:3306/automovel?createDatabaseIfNotExist=true
    username: root
    password: vini
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka